### ISSUE TITLE
Scroll sensitivity in the terminal

### ISSUE THREAD

**Issue by DamienIrving** [dit4c/tty-lean.js#1]
Scrolling in the DIT4C terminal is super sensitive, which can be problematic when teaching in front of a large audience in particular.

**Comment by tjdett** [comment]
This appears to be a problem in [term.js](https://github.com/chjj/term.js). It appears scrolling is hard-coded to 5 lines at a time.

https://github.com/chjj/term.js/blob/master/src/term.js#L1130:

``` javascript
  // allow mousewheel scrolling in
  // the shell for example
  on(el, wheelEvent, function(ev) {
    if (self.mouseEvents) return;
    if (self.applicationKeypad) return;
    if (ev.type === 'DOMMouseScroll') {
      self.scrollDisp(ev.detail < 0 ? -5 : 5);
    } else {
      self.scrollDisp(ev.wheelDeltaY > 0 ? -5 : 5);
    }
    return cancel(ev);
  });
```

<kbd>Ctrl + Up</kbd> and <kbd>Ctrl + Down</kbd> can be used to scroll 1 line at a time. <kbd>Shift + Page Up</kbd> and <kbd>Shift + Page Down</kbd> can be used to do page a time.

@DamienIrving Is this worth forking [term.js](https://github.com/chjj/term.js) to achieve, or are the keyboard shortcuts sufficient?

**Comment by tjdett** [comment]
No longer used by DIT4C, so no longer relevant.
